version: '3'

services:
  proyecto-tarjeta-credito:
    build: .
    environment:
      - PORT=5000
    deploy:
      replicas: 3
    networks:
      - red-sistema-tarjeta-credito

  nginx-proyecto-tarjeta-credito:
    build: nginx/
    container_name: nginx-tarjeta-credito-container
    ports:
      - "3000:80"
    networks:
      - red-sistema-tarjeta-credito
    depends_on:
      - proyecto-tarjeta-credito


  mysql-tarjeta-credito:
    image: mysql
    container_name: mysql-sistema-tarjeta-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sistema_tarjeta_credito
      MYSQL_USER: adonay
      MYSQL_PASSWORD: 12345
    ports:
      - "3306:3306"
    volumes:
      - mysql-proyecto:/var/lib/mysql
    networks:
      - red-sistema-tarjeta-credito
    #depends_on:
     # - rabbitmq-soporte





volumes:
  mysql-proyecto:


networks:
  red-sistema-tarjeta-credito:
    driver: bridge

