version: '3'

services:
  proyecto-tarjeta-credito: # Nombre del servicio
    build: .
    environment: # Variables de entorno
      - PORT=5000 # Variable de entorno
    deploy:
      replicas: 3
    networks:
      - red-sistema-tarjeta-credito
    depends_on:
      rabbitmq-tarjeta: # Nombre del servicio para el cual se va a verificar la salud del contenedor
        condition: service_healthy # sirve para verificar que el contenedor este corriendo el servicio y este saludable porque si no esta saludable no se puede conectar a la cola
      mysql-tarjeta:  # Nombre del servicio
        condition: service_healthy  # sirve para verificar que el contenedor este corriendo el servicio y este saludable porque si no esta saludable no se puede conectar a la base de datos

  nginx-proyecto-tarjeta-credito: # Nombre del servicio
    build: nginx/
    container_name: nginx-tarjeta-credito-container
    ports:
      - "3000:80"
    networks:
      - red-sistema-tarjeta-credito
    depends_on:
      - proyecto-tarjeta-credito # dependencia del servicio proyecto-tarjeta-credito

  rabbitmq-tarjeta: #
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-tarjeta-container
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ] # Comando para verificar la salud del contenedor
      interval: 10s # Intervalo de tiempo entre cada prueba de salud del contenedor
      timeout: 5s # Tiempo de espera para cada prueba
      retries: 5 # Número de intentos
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data_tarjeta_credito:/var/lib/rabbitmq # Volumen para almacenar los datos del contenedor
      - rabbitmq_logs_tarjeta_credito:/var/log/rabbitmq # Volumen para almacenar los logs del contenedor
    networks:
      - red-sistema-tarjeta-credito

  mysql-tarjeta: # Nombre del servicio
    image: mysql
    container_name: mysql-sistema-tarjeta-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sistema_tarjeta
      MYSQL_USER: proyecto
      MYSQL_PASSWORD: 12345
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ] # Comando para verificar la salud del contenedor
      interval: 10s # Intervalo de tiempo entre cada prueba
      timeout: 5s # Tiempo de espera para cada prueba
      retries: 5 # Número de intentos
    ports:
      - "3306:3306"
    volumes:
      - mysql-proyecto-tarjeta-credito:/var/lib/mysql # Volumen para almacenar los datos del contenedor
    networks:
      - red-sistema-tarjeta-credito

  consumidor-tarjeta: # Nombre del servicio
    build: ./consumidor           # Apunta a la carpeta 'cola'
    container_name: consumidor-tarjeta-container
    environment:
      - port=5001
    ports:
      - "5001:5001"
    networks:
      - red-sistema-tarjeta-credito
    depends_on:
      mysql-tarjeta:  # Nombre del servicio para el cual se va a verificar la salud del contenedor
        condition: service_healthy # sirve para verificar que el contenedor este corriendo el servicio y este saludable porque si no esta saludable no se puede conectar a la base de datos
      rabbitmq-tarjeta:
        condition: service_healthy # sirve para verificar que el contenedor este corriendo el servicio y este saludable porque si no esta saludable no se puede conectar a la cola


volumes:
  mysql-proyecto-tarjeta-credito: # Volumen para almacenar los datos del contenedor
  rabbitmq_data_tarjeta_credito: # Volumen para almacenar los datos del contenedor
  rabbitmq_logs_tarjeta_credito: # Volumen para almacenar los logs del contenedor


networks:
  red-sistema-tarjeta-credito: # Nombre de la red
    driver: bridge

